firstname=ABC
lastname=Dinh
email=tu@gmail.com
gender=Female
mobile=1234567890
dateOfBirth=1 February 2004
subjects=Maths,Physics
hobbies=Sports,Reading
currentAddress=abc Trieu Khuc
state=NCR
city=Delhi
modelMsg=Thanks for submitting the form