browser = chrome
username = student
password = Password123
invalidUsername = TMA
invalidPassword = 123
URL = https://practicetestautomation.com/
message = Logged In Successfully
successURL = https://practicetestautomation.com/logged-in-successfully/
